module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "accessibility-focus-inner": "var(--accessibility-focus-inner)",
        "accessibility-focus-outer": "var(--accessibility-focus-outer)",
        "brand-secondary-base": "var(--brand-secondary-base)",
        "brandprimary-base": "var(--brandprimary-base)",
        "extended-palette-blue-base": "var(--extended-palette-blue-base)",
        "extended-palette-blue-dark": "var(--extended-palette-blue-dark)",
        "extended-palette-blue-darker": "var(--extended-palette-blue-darker)",
        "extended-palette-blue-darkest": "var(--extended-palette-blue-darkest)",
        "extended-palette-blue-light": "var(--extended-palette-blue-light)",
        "extended-palette-blue-lighter": "var(--extended-palette-blue-lighter)",
        "extended-palette-blue-lightest":
          "var(--extended-palette-blue-lightest)",
        "extended-palette-cyan-base": "var(--extended-palette-cyan-base)",
        "extended-palette-cyan-dark": "var(--extended-palette-cyan-dark)",
        "extended-palette-cyan-darker": "var(--extended-palette-cyan-darker)",
        "extended-palette-cyan-darkest": "var(--extended-palette-cyan-darkest)",
        "extended-palette-cyan-light": "var(--extended-palette-cyan-light)",
        "extended-palette-cyan-lighter": "var(--extended-palette-cyan-lighter)",
        "extended-palette-cyan-lightest":
          "var(--extended-palette-cyan-lightest)",
        "extended-palette-grape-base": "var(--extended-palette-grape-base)",
        "extended-palette-grape-dark": "var(--extended-palette-grape-dark)",
        "extended-palette-grape-darker": "var(--extended-palette-grape-darker)",
        "extended-palette-grape-darkest":
          "var(--extended-palette-grape-darkest)",
        "extended-palette-grape-light": "var(--extended-palette-grape-light)",
        "extended-palette-grape-lighter":
          "var(--extended-palette-grape-lighter)",
        "extended-palette-grape-lightest":
          "var(--extended-palette-grape-lightest)",
        "extended-palette-green-base": "var(--extended-palette-green-base)",
        "extended-palette-green-dark": "var(--extended-palette-green-dark)",
        "extended-palette-green-darker": "var(--extended-palette-green-darker)",
        "extended-palette-green-darkest":
          "var(--extended-palette-green-darkest)",
        "extended-palette-green-light": "var(--extended-palette-green-light)",
        "extended-palette-green-lighter":
          "var(--extended-palette-green-lighter)",
        "extended-palette-green-lightest":
          "var(--extended-palette-green-lightest)",
        "extended-palette-indigo-base": "var(--extended-palette-indigo-base)",
        "extended-palette-indigo-dark": "var(--extended-palette-indigo-dark)",
        "extended-palette-indigo-darker":
          "var(--extended-palette-indigo-darker)",
        "extended-palette-indigo-darkest":
          "var(--extended-palette-indigo-darkest)",
        "extended-palette-indigo-light": "var(--extended-palette-indigo-light)",
        "extended-palette-indigo-lighter":
          "var(--extended-palette-indigo-lighter)",
        "extended-palette-indigo-lightest":
          "var(--extended-palette-indigo-lightest)",
        "extended-palette-lime-base": "var(--extended-palette-lime-base)",
        "extended-palette-lime-dark": "var(--extended-palette-lime-dark)",
        "extended-palette-lime-darker": "var(--extended-palette-lime-darker)",
        "extended-palette-lime-darkest": "var(--extended-palette-lime-darkest)",
        "extended-palette-lime-light": "var(--extended-palette-lime-light)",
        "extended-palette-lime-lighter": "var(--extended-palette-lime-lighter)",
        "extended-palette-lime-lightest":
          "var(--extended-palette-lime-lightest)",
        "extended-palette-orange-base": "var(--extended-palette-orange-base)",
        "extended-palette-orange-dark": "var(--extended-palette-orange-dark)",
        "extended-palette-orange-darker":
          "var(--extended-palette-orange-darker)",
        "extended-palette-orange-darkest":
          "var(--extended-palette-orange-darkest)",
        "extended-palette-orange-light": "var(--extended-palette-orange-light)",
        "extended-palette-orange-lighter":
          "var(--extended-palette-orange-lighter)",
        "extended-palette-orange-lightest":
          "var(--extended-palette-orange-lightest)",
        "extended-palette-pink-base": "var(--extended-palette-pink-base)",
        "extended-palette-pink-dark": "var(--extended-palette-pink-dark)",
        "extended-palette-pink-darker": "var(--extended-palette-pink-darker)",
        "extended-palette-pink-darkest": "var(--extended-palette-pink-darkest)",
        "extended-palette-pink-light": "var(--extended-palette-pink-light)",
        "extended-palette-pink-lighter": "var(--extended-palette-pink-lighter)",
        "extended-palette-pink-lightest":
          "var(--extended-palette-pink-lightest)",
        "extended-palette-red-base": "var(--extended-palette-red-base)",
        "extended-palette-red-dark": "var(--extended-palette-red-dark)",
        "extended-palette-red-darker": "var(--extended-palette-red-darker)",
        "extended-palette-red-darkest": "var(--extended-palette-red-darkest)",
        "extended-palette-red-light": "var(--extended-palette-red-light)",
        "extended-palette-red-lighter": "var(--extended-palette-red-lighter)",
        "extended-palette-red-lightest": "var(--extended-palette-red-lightest)",
        "extended-palette-teal-base": "var(--extended-palette-teal-base)",
        "extended-palette-teal-dark": "var(--extended-palette-teal-dark)",
        "extended-palette-teal-darker": "var(--extended-palette-teal-darker)",
        "extended-palette-teal-darkest": "var(--extended-palette-teal-darkest)",
        "extended-palette-teal-light": "var(--extended-palette-teal-light)",
        "extended-palette-teal-lighter": "var(--extended-palette-teal-lighter)",
        "extended-palette-teal-lightest":
          "var(--extended-palette-teal-lightest)",
        "extended-palette-violet-base": "var(--extended-palette-violet-base)",
        "extended-palette-violet-dark": "var(--extended-palette-violet-dark)",
        "extended-palette-violet-darker":
          "var(--extended-palette-violet-darker)",
        "extended-palette-violet-darkest":
          "var(--extended-palette-violet-darkest)",
        "extended-palette-violet-light": "var(--extended-palette-violet-light)",
        "extended-palette-violet-lighter":
          "var(--extended-palette-violet-lighter)",
        "extended-palette-violet-lightest":
          "var(--extended-palette-violet-lightest)",
        "extended-palette-yellow-base": "var(--extended-palette-yellow-base)",
        "extended-palette-yellow-dark": "var(--extended-palette-yellow-dark)",
        "extended-palette-yellow-darker":
          "var(--extended-palette-yellow-darker)",
        "extended-palette-yellow-darkest":
          "var(--extended-palette-yellow-darkest)",
        "extended-palette-yellow-light": "var(--extended-palette-yellow-light)",
        "extended-palette-yellow-lighter":
          "var(--extended-palette-yellow-lighter)",
        "extended-palette-yellow-lightest":
          "var(--extended-palette-yellow-lightest)",
        "layout-colors-content": "var(--layout-colors-content)",
        "layout-colors-login": "var(--layout-colors-login)",
        "layout-colorsheader": "var(--layout-colorsheader)",
        "neutral-neutral-0": "var(--neutral-neutral-0)",
        "neutral-neutral-1": "var(--neutral-neutral-1)",
        "neutral-neutral-10": "var(--neutral-neutral-10)",
        "neutral-neutral-2": "var(--neutral-neutral-2)",
        "neutral-neutral-3": "var(--neutral-neutral-3)",
        "neutral-neutral-4": "var(--neutral-neutral-4)",
        "neutral-neutral-5": "var(--neutral-neutral-5)",
        "neutral-neutral-7": "var(--neutral-neutral-7)",
        "neutral-neutral-9": "var(--neutral-neutral-9)",
        "neutralneutral-6": "var(--neutralneutral-6)",
        "neutralneutral-8": "var(--neutralneutral-8)",
        semanticerrorbase: "var(--semanticerrorbase)",
        semanticerrorlight: "var(--semanticerrorlight)",
        semanticinfobase: "var(--semanticinfobase)",
        semanticinfolight: "var(--semanticinfolight)",
        semanticsuccessbase: "var(--semanticsuccessbase)",
        semanticsuccesslight: "var(--semanticsuccesslight)",
        semanticwarningbase: "var(--semanticwarningbase)",
        semanticwarninglight: "var(--semanticwarninglight)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "actions-base": "var(--actions-base-font-family)",
        "actions-s": "var(--actions-s-font-family)",
        "actions-XS": "var(--actions-XS-font-family)",
        "actions-XS-bold": "var(--actions-XS-bold-font-family)",
        "desktop-body-base": "var(--desktop-body-base-font-family)",
        "desktop-body-s": "var(--desktop-body-s-font-family)",
        "desktop-body-XS": "var(--desktop-body-XS-font-family)",
        "desktop-display-bold": "var(--desktop-display-bold-font-family)",
        "desktop-display-light": "var(--desktop-display-light-font-family)",
        "desktop-display-regular": "var(--desktop-display-regular-font-family)",
        "desktop-display-semibold":
          "var(--desktop-display-semibold-font-family)",
        "desktop-h1-bold": "var(--desktop-h1-bold-font-family)",
        "desktop-h1-light": "var(--desktop-h1-light-font-family)",
        "desktop-h1-regular": "var(--desktop-h1-regular-font-family)",
        "desktop-h1-semibold": "var(--desktop-h1-semibold-font-family)",
        "desktop-h2-bold": "var(--desktop-h2-bold-font-family)",
        "desktop-h2-light": "var(--desktop-h2-light-font-family)",
        "desktop-h2-regular": "var(--desktop-h2-regular-font-family)",
        "desktop-h2-semibold": "var(--desktop-h2-semibold-font-family)",
        "desktop-h3-bold": "var(--desktop-h3-bold-font-family)",
        "desktop-h3-light": "var(--desktop-h3-light-font-family)",
        "desktop-h3-regular": "var(--desktop-h3-regular-font-family)",
        "desktop-h3-semibold": "var(--desktop-h3-semibold-font-family)",
        "desktop-h4-bold": "var(--desktop-h4-bold-font-family)",
        "desktop-h4-light": "var(--desktop-h4-light-font-family)",
        "desktop-h4-regular": "var(--desktop-h4-regular-font-family)",
        "desktop-h4-semibold": "var(--desktop-h4-semibold-font-family)",
        "desktop-h5-bold": "var(--desktop-h5-bold-font-family)",
        "desktop-h5-light": "var(--desktop-h5-light-font-family)",
        "desktop-h5-regular": "var(--desktop-h5-regular-font-family)",
        "desktop-h5-semibold": "var(--desktop-h5-semibold-font-family)",
        "desktop-h6-bold": "var(--desktop-h6-bold-font-family)",
        "desktop-h6-light": "var(--desktop-h6-light-font-family)",
        "desktop-h6-regular": "var(--desktop-h6-regular-font-family)",
        "desktop-h6-semibold": "var(--desktop-h6-semibold-font-family)",
        "phone-body-base": "var(--phone-body-base-font-family)",
        "phone-body-s": "var(--phone-body-s-font-family)",
        "phone-body-XS": "var(--phone-body-XS-font-family)",
        "phone-display-bold": "var(--phone-display-bold-font-family)",
        "phone-display-light": "var(--phone-display-light-font-family)",
        "phone-display-regular": "var(--phone-display-regular-font-family)",
        "phone-display-semibold": "var(--phone-display-semibold-font-family)",
        "phone-h1-bold": "var(--phone-h1-bold-font-family)",
        "phone-h1-light": "var(--phone-h1-light-font-family)",
        "phone-h1-regular": "var(--phone-h1-regular-font-family)",
        "phone-h1-semibold": "var(--phone-h1-semibold-font-family)",
        "phone-h2-bold": "var(--phone-h2-bold-font-family)",
        "phone-h2-light": "var(--phone-h2-light-font-family)",
        "phone-h2-regular": "var(--phone-h2-regular-font-family)",
        "phone-h2-semibold": "var(--phone-h2-semibold-font-family)",
        "phone-h3-bold": "var(--phone-h3-bold-font-family)",
        "phone-h3-light": "var(--phone-h3-light-font-family)",
        "phone-h3-regular": "var(--phone-h3-regular-font-family)",
        "phone-h3-semibold": "var(--phone-h3-semibold-font-family)",
        "phone-h4-bold": "var(--phone-h4-bold-font-family)",
        "phone-h4-light": "var(--phone-h4-light-font-family)",
        "phone-h4-regular": "var(--phone-h4-regular-font-family)",
        "phone-h4-semibold": "var(--phone-h4-semibold-font-family)",
        "phone-h5-bold": "var(--phone-h5-bold-font-family)",
        "phone-h5-light": "var(--phone-h5-light-font-family)",
        "phone-h5-regular": "var(--phone-h5-regular-font-family)",
        "phone-h5-semibold": "var(--phone-h5-semibold-font-family)",
        "phone-h6-bold": "var(--phone-h6-bold-font-family)",
        "phone-h6-light": "var(--phone-h6-light-font-family)",
        "phone-h6-regular": "var(--phone-h6-regular-font-family)",
        "phone-h6-semibold": "var(--phone-h6-semibold-font-family)",
        "tablet-body-base": "var(--tablet-body-base-font-family)",
        "tablet-body-s": "var(--tablet-body-s-font-family)",
        "tablet-body-XS": "var(--tablet-body-XS-font-family)",
        "tablet-display-bold": "var(--tablet-display-bold-font-family)",
        "tablet-display-light": "var(--tablet-display-light-font-family)",
        "tablet-display-regular": "var(--tablet-display-regular-font-family)",
        "tablet-display-semibold": "var(--tablet-display-semibold-font-family)",
        "tablet-h1-bold": "var(--tablet-h1-bold-font-family)",
        "tablet-h1-light": "var(--tablet-h1-light-font-family)",
        "tablet-h1-regular": "var(--tablet-h1-regular-font-family)",
        "tablet-h1-semibold": "var(--tablet-h1-semibold-font-family)",
        "tablet-h2-bold": "var(--tablet-h2-bold-font-family)",
        "tablet-h2-light": "var(--tablet-h2-light-font-family)",
        "tablet-h2-regular": "var(--tablet-h2-regular-font-family)",
        "tablet-h2-semibold": "var(--tablet-h2-semibold-font-family)",
        "tablet-h3-bold": "var(--tablet-h3-bold-font-family)",
        "tablet-h3-light": "var(--tablet-h3-light-font-family)",
        "tablet-h3-regular": "var(--tablet-h3-regular-font-family)",
        "tablet-h3-semibold": "var(--tablet-h3-semibold-font-family)",
        "tablet-h4-bold": "var(--tablet-h4-bold-font-family)",
        "tablet-h4-light": "var(--tablet-h4-light-font-family)",
        "tablet-h4-regular": "var(--tablet-h4-regular-font-family)",
        "tablet-h4-semibold": "var(--tablet-h4-semibold-font-family)",
        "tablet-h5-bold": "var(--tablet-h5-bold-font-family)",
        "tablet-h5-light": "var(--tablet-h5-light-font-family)",
        "tablet-h5-regular": "var(--tablet-h5-regular-font-family)",
        "tablet-h5-semibold": "var(--tablet-h5-semibold-font-family)",
        "tablet-h6-bold": "var(--tablet-h6-bold-font-family)",
        "tablet-h6-light": "var(--tablet-h6-light-font-family)",
        "tablet-h6-regular": "var(--tablet-h6-regular-font-family)",
        "tablet-h6-semibold": "var(--tablet-h6-semibold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "button-state-focus": "var(--button-state-focus)",
        "shadow-l": "var(--shadow-l)",
        "shadow-m": "var(--shadow-m)",
        "shadow-none": "var(--shadow-none)",
        "shadow-s": "var(--shadow-s)",
        "shadow-XL": "var(--shadow-XL)",
        "shadow-XS": "var(--shadow-XS)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
